definitions:
  steps:
    - step: &build
        image: golang:1.15.8
        script:
          - make build
        artifacts:
          - bin/**
          - Makefile
          - template.yaml
    - step: &zip
        image: atlassian/default-image:2
        script:
          - make zip
        artifacts:
          - bin/**/*.zip
          - template.yaml
    - step: &deploy
        script:
          - pipe: atlassian/aws-sam-deploy:0.5.2
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: $S3_BUCKET
              STACK_NAME: $STACK_NAME
              CAPABILITIES:
                - CAPABILITY_IAM
                - CAPABILITY_NAMED_IAM
                - CAPABILITY_AUTO_EXPAND
              SAM_TEMPLATE: template.yaml
              WAIT: 'true'
              WAIT_INTERVAL: 60
              DEBUG: 'true'
              STACK_PARAMETERS: |
                [
                  {
                    "ParameterKey": "PostgreSQLUsername",
                    "ParameterValue": "${POSTGRESQL_USERNAME}"
                  },
                  {
                    "ParameterKey": "PostgreSQLPassword",
                    "ParameterValue": "${POSTGRESQL_PASSWORD}"
                  },
                  {
                    "ParameterKey": "PostgreSQLHost",
                    "ParameterValue": "${POSTGRESQL_HOST}"
                  },
                  {
                    "ParameterKey": "PostgreSQLPort",
                    "ParameterValue": "${POSTGRESQL_PORT}"
                  },
                  {
                    "ParameterKey": "PostgreSQLDBName",
                    "ParameterValue": "${POSTGRESQL_DB_NAME}"
                  },
                  {
                    "ParameterKey": "EnvironmentName",
                    "ParameterValue": "${ENVIRONMENT_NAME}"
                  },
                  {
                    "ParameterKey": "TelegramBotURL",
                    "ParameterValue": "${TELEGRAM_BOT_URL}"
                  },
                  {
                    "ParameterKey": "FacebookMessengerBotURL",
                    "ParameterValue": "${FACEBOOK_MESSENGER_BOT_URL}"
                  },
                  {
                    "ParameterKey": "FacebookMessengerBotVerifyToken",
                    "ParameterValue": "${FACEBOOK_MESSENGER_BOT_VERIFY_TOKEN}"
                  },
                  {
                    "ParameterKey": "FacebookAppId",
                    "ParameterValue": "${FACEBOOK_APP_ID}"
                  },
                  {
                    "ParameterKey": "FacebookAppSecret",
                    "ParameterValue": "${FACEBOOK_APP_SECRET}"
                  },
                  {
                    "ParameterKey": "InstagramPrivateBotURL",
                    "ParameterValue": "${INSTAGRAM_PRIVATE_BOT_URL}"
                  }
                ]

pipelines:
  branches:
    develop:
      - step: *build
      - step: *zip
      - step:
          <<: *deploy
          deployment: develop
    master:
      - step: *build
      - step: *zip
      - step:
          <<: *deploy
          deployment: master