AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  PostgreSQLUsername:
    Type: String
  PostgreSQLPassword:
    Type: String
  PostgreSQLHost:
    Type: String
  PostgreSQLPort:
    Type: String
  PostgreSQLDBName:
    Type: String
  EnvironmentName:
    Type: String

Globals:
  Function:
    Runtime: go1.x
    MemorySize: 128
    Timeout: 30
    Environment:
      Variables:
        POSTGRESQL_USERNAME:
          'Fn::Sub': '${PostgreSQLUsername}'
        POSTGRESQL_PASSWORD:
          'Fn::Sub': '${PostgreSQLPassword}'
        POSTGRESQL_HOST:
          'Fn::Sub': '${PostgreSQLHost}'
        POSTGRESQL_PORT:
          'Fn::Sub': '${PostgreSQLPort}'
        POSTGRESQL_DB_NAME:
          'Fn::Sub': '${PostgreSQLDBName}'

Resources:
  CreateOrganizationSettings:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName:
        'Fn::Sub': '${EnvironmentName}CreateOrganizationSettings'
      CodeUri: bin/organizationsettings/createorganizationsettings.zip
      Handler: bin/organizationsettings/createorganizationsettings
  DeleteOrganizationSettings:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName:
        'Fn::Sub': '${EnvironmentName}DeleteOrganizationSettings'
      CodeUri: bin/organizationsettings/deleteorganizationsettings.zip
      Handler: bin/organizationsettings/deleteorganizationsettings
  GetOrganizationSettings:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName:
        'Fn::Sub': '${EnvironmentName}GetOrganizationSettings'
      CodeUri: bin/organizationsettings/getorganizationsettings.zip
      Handler: bin/organizationsettings/getorganizationsettings
  UpdateOrganizationSettings:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName:
        'Fn::Sub': '${EnvironmentName}UpdateOrganizationSettings'
      CodeUri: bin/organizationsettings/updateorganizationsettings.zip
      Handler: bin/organizationsettings/updateorganizationsettings


Outputs:
  CreateOrganizationSettingsARN:
    Value:
      'Fn::GetAtt': CreateOrganizationSettings.Arn
    Export:
      Name:
        'Fn::Sub': '${AWS::StackName}:${EnvironmentName}CreateOrganizationSettingsARN'
  DeleteOrganizationSettingsARN:
    Value:
      'Fn::GetAtt': DeleteOrganizationSettings.Arn
    Export:
      Name:
        'Fn::Sub': '${AWS::StackName}:${EnvironmentName}DeleteOrganizationSettingsARN'
  GetOrganizationSettingsARN:
    Value:
      'Fn::GetAtt': GetOrganizationSettings.Arn
    Export:
      Name:
        'Fn::Sub': '${AWS::StackName}:${EnvironmentName}GetOrganizationSettingsARN'
  UpdateOrganizationSettingsARN:
    Value:
      'Fn::GetAtt': UpdateOrganizationSettings.Arn
    Export:
      Name:
        'Fn::Sub': '${AWS::StackName}:${EnvironmentName}UpdateOrganizationSettingsARN'